[project]
name = "fpl-optimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "ortools>=9.14.6206",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
